server:
  port: 8182
  host: 0.0.0.0
catalogs:
  - name: sqlite-catalog-demo
    type: jdbc
    uri: jdbc:sqlite:file:./catalog.db
    jdbc.schema-version: V1
    warehouse: ./data
  - name: rest-catalog-demo
    type: rest
    uri: http://localhost:8181
    warehouse: s3://warehouse/
