server:
  port: 8182
  host: 0.0.0.0
catalogs:
  - name: sqlite-catalog-demo
    catalog-impl: org.apache.iceberg.jdbc.JdbcCatalog
    uri: jdbc:sqlite:file:./catalog.db
    jdbc.schema-version: V1
    warehouse: ./data
